trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'azureServiceConnection'   # Azure DevOps service connection name
  aksClusterName: 'aks-cluster'
  aksResourceGroup: 'rg-landing-zone'
  containerRegistry: 'myacr.azurecr.io'         # Replace with your ACR login server
  imageName: 'myapp'
  helmReleaseName: 'myapp'
  helmChartPath: './helm/myapp-chart'
  keyVaultName: 'rg-landing-zone-kv'

stages:

# ===============================
# 1. CI: Terraform Plan
# ===============================
- stage: terraform
  displayName: 'CI – Terraform Plan'
  jobs:
    - job: terraform
      displayName: 'Run Terraform Plan'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.6.0'

        - checkout: self

        - script: terraform init
          displayName: 'Terraform Init'

        - script: terraform validate
          displayName: 'Terraform Validate'

        - script: terraform plan -out=tfplan
          displayName: 'Terraform Plan'

        - publish: tfplan
          artifact: terraformPlan
          displayName: 'Publish Terraform Plan Artifact'


# ===============================
# 2. CD: Terraform Apply (Manual Approval)
# ===============================
- stage: terraform_apply
  displayName: 'CD – Apply Terraform Plan'
  dependsOn: terraform
  condition: succeeded()
  jobs:
    - job: apply
      displayName: 'Terraform Apply'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - download: current
          artifact: terraformPlan
          displayName: 'Download Terraform Plan'

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: '1.6.0'

        - checkout: self

        - script: terraform init
          displayName: 'Terraform Init'

        - script: terraform apply -auto-approve tfplan
          displayName: 'Terraform Apply'


# ===============================
# 3. CI: Build and Push Docker Image
# ===============================
- stage: build
  displayName: 'CI – Build & Push Docker Image'
  dependsOn: terraform_apply
  jobs:
    - job: docker
      displayName: 'Docker Build & Push'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self

        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az acr login --name $(containerRegistry)
              docker build -t $(containerRegistry)/$(imageName):$(Build.BuildId) .
              docker push $(containerRegistry)/$(imageName):$(Build.BuildId)


# ===============================
# 4. CD: Deploy to AKS using Helm
# ===============================
- stage: deploy
  displayName: 'CD – Deploy to AKS with Helm'
  dependsOn: build
  jobs:
    - deployment: helmDeploy
      displayName: 'Helm Deploy'
      environment: 'aks-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "Getting AKS credentials..."
                    az aks get-credentials --name $(aksClusterName) --resource-group $(aksResourceGroup) --overwrite-existing

                    echo "Deploying with Helm..."
                    helm upgrade --install $(helmReleaseName) $(helmChartPath) \
                      --set image.repository=$(containerRegistry)/$(imageName) \
                      --set image.tag=$(Build.BuildId)


# ===============================
# 5. CD: Post-deploy Monitoring Check
# ===============================
- stage: monitor
  displayName: 'CD – Post-deploy Monitoring Check'
  dependsOn: deploy
  jobs:
    - job: verify
      displayName: 'Verify Prometheus/Grafana Pods'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Checking Prometheus & Grafana health..."
              az aks get-credentials --name $(aksClusterName) --resource-group $(aksResourceGroup) --overwrite-existing

              kubectl get pods -n default | grep prometheus
              kubectl get pods -n default | grep grafana
