trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'azureServiceConnection'
  aksClusterName: 'aks-cluster'
  aksResourceGroup: 'rg-landing-zone'
  acrName: 'myacr'
  containerRegistry: 'myacr.azurecr.io'
  imageName: 'myapp'
  helmReleaseName: 'myapp'
  helmChartPath: './helm/myapp-chart'
  keyVaultName: 'rg-landing-zone-kv'

stages:

# ===============================
# 1. CI: Terraform Plan
# ===============================
- stage: terraform
  displayName: 'CI – Terraform Plan'
  jobs:
    - job: terraform
      displayName: 'Run Terraform Plan'
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

        - script: |
            echo "Installing Terraform..."
            curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
            unzip -o terraform.zip
            sudo mv terraform /usr/local/bin/
            terraform version
          displayName: 'Install & Check Terraform Version'

        - task: AzureCLI@2
          name: exportCreds
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Exporting Azure credentials..."
              echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
              echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
              echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
              echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"

        - script: terraform init
          workingDirectory: landing-zone
          displayName: 'Terraform Init'

        - script: |
            terraform plan -out=tfplan.out \
              -var="subscription_id=$(ARM_SUBSCRIPTION_ID)" \
              -var="client_id=$(ARM_CLIENT_ID)" \
              -var="client_secret=$(ARM_CLIENT_SECRET)" \
              -var="tenant_id=$(ARM_TENANT_ID)"
          workingDirectory: landing-zone
          displayName: 'Terraform Plan'

        - publish: landing-zone/tfplan.out
          artifact: terraformPlan
          displayName: 'Publish Terraform Plan Artifact'

# ===============================
# 2. CD: Terraform Apply (Manual Approval)
# ===============================
- stage: terraform_apply
  displayName: 'CD – Apply Terraform Plan'
  dependsOn: terraform
  condition: succeeded()
  jobs:
    - deployment: apply
      displayName: 'Terraform Apply'
      environment: 'infra-approval'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: terraformPlan

              - checkout: self

              - script: |
                  echo "Installing Terraform..."
                  curl -s -o terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
                  unzip -o terraform.zip
                  sudo mv terraform /usr/local/bin/
                  terraform version
                displayName: 'Install & Check Terraform Version'

              - task: AzureCLI@2
                name: exportCreds
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "Exporting Azure credentials..."
                    echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
                    echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
                    echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$servicePrincipalKey"
                    echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"

              - script: terraform init
                workingDirectory: landing-zone
                displayName: 'Terraform Init'

              - script: |
                  terraform apply -auto-approve tfplan.out \
                    -var="subscription_id=$(ARM_SUBSCRIPTION_ID)" \
                    -var="client_id=$(ARM_CLIENT_ID)" \
                    -var="client_secret=$(ARM_CLIENT_SECRET)" \
                    -var="tenant_id=$(ARM_TENANT_ID)"
                workingDirectory: landing-zone
                displayName: 'Terraform Apply'

# ===============================
# 3. CI: Build and Push Docker Image
# ===============================
- stage: build
  displayName: 'CI – Build & Push Docker Image'
  dependsOn: terraform_apply
  jobs:
    - job: docker
      displayName: 'Docker Build & Push'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - checkout: self

        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              docker build -t $(containerRegistry)/$(imageName):$(Build.BuildId) .
              docker push $(containerRegistry)/$(imageName):$(Build.BuildId)

# ===============================
# 4. CD: Deploy to AKS using Helm
# ===============================
- stage: deploy
  displayName: 'CD – Deploy to AKS with Helm'
  dependsOn: build
  jobs:
    - deployment: helmDeploy
      displayName: 'Helm Deploy'
      environment: 'aks-dev'
      strategy:
        runOnce:
          deploy:
            steps:
              - checkout: self

              - task: AzureCLI@2
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: 'bash'
                  scriptLocation: 'inlineScript'
                  inlineScript: |
                    echo "Getting AKS credentials..."
                    az aks get-credentials --name $(aksClusterName) --resource-group $(aksResourceGroup) --overwrite-existing

                    echo "Deploying with Helm..."
                    helm lint $(helmChartPath)
                    helm upgrade --install $(helmReleaseName) $(helmChartPath) \
                      --set image.repository=$(containerRegistry)/$(imageName) \
                      --set image.tag=$(Build.BuildId)

# ===============================
# 5. CD: Post-deploy Monitoring Check
# ===============================
- stage: monitor
  displayName: 'CD – Post-deploy Monitoring Check'
  dependsOn: deploy
  jobs:
    - job: verify
      displayName: 'Verify Prometheus/Grafana Pods'
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              echo "Checking Prometheus & Grafana health..."
              az aks get-credentials --name $(aksClusterName) --resource-group $(aksResourceGroup) --overwrite-existing

              kubectl get pods -n default | grep prometheus
              kubectl get pods -n default | grep grafana
              if [ $? -ne 0 ]; then
                echo "Prometheus or Grafana pods are not running!"
                exit 1
              else
                echo "Prometheus and Grafana pods are running successfully."
              fi
